import Head from 'next/head';
import { api } from '@/api';
import { parseRangeFromQuery } from '@/utils/serverParsers';
import ProductsClientPage from './_clientpage';

export default async function ProductsPage({
  searchParams,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
  const urlRange = (await searchParams).range;

  // TODO Fix to work with server componet
  const [start, end] = parseRangeFromQuery(urlRange);
  const products = await api.products.findMany({
    range: [start, end],
  });

  // TODO fix pagination which is probably broken
  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductsClientPage products={products} />
    </>
  );
}
