version: '3'
name: minas_phone_prod

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:8080
    environment:
      - NODE_ENV=production
