import Head from 'next/head';
import { useEffect } from 'react';
import { Container, Grid } from '@mui/material';

import { MainContainer, ToolBar } from '@/components/Category/Products/styles';
import ProductCard from '@/components/Category/Products/ProductCard/ProductCard';
import Spinner from '@/components/Spinner/Spinner';
import Filter from '@/components/Category/Filter/Filter';
import { api } from '@/api';
import { ProductPaginatedResponse } from '@/api/types/products';
import { GetServerSideProps } from 'next';

interface ProductsProps {
  products: ProductPaginatedResponse;
}

export const getServerSideProps: GetServerSideProps<
  ProductsProps
> = async () => {
  const products = await api.products.findMany({
    limit: 10,
    page: 0,
  });
  return { props: { products } };
};

export default function Landing({ products }: ProductsProps) {
  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <ToolBar />
        <Container sx={{ pb: 20 }}>
          <Grid container justifyContent="center" spacing={4}>
            {/* <Hidden xsDown> */}
            <Grid
              item
              xs={0}
              sm={3}
              sx={{ display: { xs: 'none', md: 'block' } }}
            >
              <Filter />
            </Grid>
            <Grid item container xs={12} sm={9} spacing={4}>
              {products.data.map((product) => (
                <Grid
                  item
                  key={product.id}
                  xs={12}
                  md={6}
                  lg={4}
                  // sx={{ borderColor: 'red', borderWidth: 1, borderStyle: 'solid' }}
                >
                  <ProductCard product={product} />
                </Grid>
              ))}
            </Grid>
          </Grid>
        </Container>
      </MainContainer>
    </>
  );
}
