http://localhost:8080/api/v1/products/
### Create a product (& upload an image)
POST http://localhost:8080/api/v1/products/
content-type: multipart/form-data
--MyBoundary
Content-Disposition: form-data; name="data"

{"active":true,"slug":"prod_1523","name":"iphone","description":"description-xd-xd","quantity":5,"media":"sku1","sku":"sku1","price":1}
--MyBoundary
Content-Disposition: form-data; name="image"; filename="iphone11.jpeg"
Content-Type: image/jpeg

< ./iphone11.jpeg

--MyBoundary--

### Get all products
GET http://localhost:8080/api/v1/products/
