version: '3'
name: minas_phone_dev

# # Copy env files
# COPY .env.prod .
# COPY .development.docker.env .

services:
  api:
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - supertokens
    networks:
      - app_network
    environment:
      - NODE_ENV=development:docker
      - DB_DOCKER_HOST=db
      - ST_DOCKER_URI=http://supertokens:3567
    env_file:
      - '../../.env.development'

  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    user: ${DB_USERNAME}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@email.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - 5050:80
  #   networks:
  #     - postgres

  # Note: If you are assigning a custom name to your db service on the line below, make sure it does not contain underscores
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: supertokens_user
      POSTGRES_PASSWORD: somePassword
      POSTGRES_DB: supertokens
    expose:
      - '5433' # Publishes 5433 to other containers but NOT to host machine
    ports:
      - '5433:5433'
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-p',
          '5433',
          '-U',
          'supertokens_user',
          '-d',
          'supertokens',
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: -p 5433

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:6.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: 'postgresql://supertokens_user:somePassword@db:5433/supertokens'
      POSTGRESQL_TABLE_SCHEMA: 'supertokens'
      API_KEYS: ${SUPERTOKENS_API_KEYS}
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app_network:
    driver: bridge
volumes:
  postgres-data:
  auth-db-data:
