import Head from 'next/head';
import { useEffect } from 'react';
import { Container, Grid } from '@mui/material';

import { MainContainer, ToolBar } from '@/components/Category/Products/styles';
import ProductCard from '@/components/Category/Products/ProductCard/ProductCard';
import Spinner from '@/components/Spinner/Spinner';
import Filter from '@/components/Category/Filter/Filter';
import { api } from '@/api';
import { ProductPaginatedResponse } from '@/api/types/products';
import { GetServerSideProps } from 'next';
import Products from '@/components/Category/Products/Products';

interface ProductsProps {
  products: ProductPaginatedResponse;
}

export const getServerSideProps: GetServerSideProps<
  ProductsProps
> = async () => {
  const products = await api.products.findMany({
    limit: 10,
    page: 0,
  });
  return { props: { products } };
};

export default function ProductsPage({ products }: ProductsProps) {
  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Products products={products.data} />
    </>
  );
}
