export const PRODUCT_REPO = 'PRODUCT_REPO';
export const CATEGORY_REPO = 'CATEGORY_REPO';
export const CLOUD_STORAGE_SERVICE = 'CLOUD_STORAGE_SERVICE';

export const ATTRIBUTE_REPO = 'ATTRIBUTE_REPO';
export const PRODUCT_TYPE_REPO = 'PRODUCT_TYPE_REPO';
