name: Node Continuous Integration

on:
  pull_request:
    paths:
      - 'server/**'
    branches: ['main']

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: cd server
      - run: npm ci
      - run: npm run build
